services:
  geoswitch:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoswitch:dev
    container_name: geoswitch
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env