services:
  geoswitch:
    image: geoswitch:dev
    container_name: geoswitch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - geoswitch-net
    env_file:
      - .env

networks:
  geoswitch-net:
    name: geoswitch-net